window.HSK1_DECK = [
  { script: "爱", romanization: "ài", meaning: "to love" },
  { script: "八", romanization: "bā", meaning: "eight" },
  { script: "爸爸", romanization: "bà ba", meaning: "dad" },
  { script: "杯子", romanization: "bēi zi", meaning: "cup" },
  { script: "北京", romanization: "Běi jīng", meaning: "Beijing" },
  { script: "本", romanization: "běn", meaning: "root" },
  { script: "不客气", romanization: "bù kè qi", meaning: "you're welcome" },
  { script: "不", romanization: "bù", meaning: "(negative prefix)" },
  { script: "菜", romanization: "cài", meaning: "dish (type of food)" },
  { script: "茶", romanization: "chá", meaning: "tea" },
  { script: "吃", romanization: "chī", meaning: "to eat" },
  { script: "出租车", romanization: "chū zū chē", meaning: "taxi" },
  { script: "大", romanization: "dà", meaning: "big" },
  { script: "的", romanization: "de", meaning: "of" },
  { script: "点", romanization: "diǎn", meaning: "point" },
  { script: "电脑", romanization: "diàn nǎo", meaning: "computer" },
  { script: "电视", romanization: "diàn shì", meaning: "television" },
  { script: "电影", romanization: "diàn yǐng", meaning: "movie" },
  { script: "东西", romanization: "dōng xi", meaning: "thing" },
  { script: "都", romanization: "dōu", meaning: "all" },
  { script: "读", romanization: "dú", meaning: "to read" },
  { script: "对不起", romanization: "duì bu qǐ", meaning: "unworthy" },
  { script: "多", romanization: "duō", meaning: "many" },
  { script: "多少", romanization: "duō shao", meaning: "how much" },
  { script: "儿子", romanization: "ér zi", meaning: "son" },
  { script: "二", romanization: "èr", meaning: "two" },
  { script: "饭馆", romanization: "fàn guǎn", meaning: "restaurant" },
  { script: "个", romanization: "gè", meaning: "particle" },
  { script: "狗", romanization: "gǒu", meaning: "dog" },
  { script: "好", romanization: "hǎo", meaning: "good" },
  { script: "喝", romanization: "hē", meaning: "to drink" },
  { script: "和", romanization: "hé", meaning: "and" },
  { script: "很", romanization: "hěn", meaning: "(adverb of degree)" },
  { script: "会", romanization: "huì", meaning: "can" },
  { script: "火车站", romanization: "huǒ chē zhàn", meaning: "train station" },
  { script: "几", romanization: "jǐ", meaning: "how much" },
  { script: "家", romanization: "jiā", meaning: "home" },
  { script: "叫", romanization: "jiào", meaning: "to shout" },
  { script: "今天", romanization: "jīn tiān", meaning: "today" },
  { script: "九", romanization: "jiǔ", meaning: "nine" },
  { script: "看", romanization: "kàn", meaning: "to see" },
  { script: "看见", romanization: "kàn jiàn", meaning: "to see" },
  { script: "块", romanization: "kuài", meaning: "piece" },
  { script: "老师", romanization: "lǎo shī", meaning: "teacher" },
  { script: "了", romanization: "le", meaning: "(modal particle intensifying preceding clause)" },
  { script: "冷", romanization: "lěng", meaning: "cold" },
  { script: "妈妈", romanization: "mā ma", meaning: "mama" },
  { script: "六", romanization: "liù", meaning: "six" },
  { script: "吗", romanization: "ma", meaning: "question" },
  { script: "买", romanization: "mǎi", meaning: "to buy" },
  { script: "猫", romanization: "māo", meaning: "cat" },
  { script: "没", romanization: "méi", meaning: "negative" },
  { script: "没关系", romanization: "méi guān xi", meaning: "it doesn't matter" },
  { script: "米饭", romanization: "mǐ fàn", meaning: "cooked rice" },
  { script: "明天", romanization: "míng tiān", meaning: "tomorrow" },
  { script: "名字", romanization: "míng zi", meaning: "name" },
  { script: "你", romanization: "nǐ", meaning: "you" },
  { script: "是", romanization: "shì", meaning: "is" },
  { script: "书", romanization: "shū", meaning: "book" },
  { script: "水", romanization: "shuǐ", meaning: "water" },
  { script: "水果", romanization: "shuǐ guǒ", meaning: "fruit" },
  { script: "女儿", romanization: "nǚ ér", meaning: "daughter" },
  { script: "朋友", romanization: "péng you", meaning: "friend" },
  { script: "漂亮", romanization: "piào liang", meaning: "pretty" },
  { script: "苹果", romanization: "píng guǒ", meaning: "apple" },
  { script: "七", romanization: "qī", meaning: "seven" },
  { script: "去", romanization: "qù", meaning: "to go" },
  { script: "人", romanization: "rén", meaning: "man" },
  { script: "我", romanization: "wǒ", meaning: "I" },
  { script: "我们", romanization: "wǒ men", meaning: "we" },
  { script: "五", romanization: "wǔ", meaning: "five" },
  { script: "喜欢", romanization: "xǐ huan", meaning: "to like" },
  { script: "下雨", romanization: "xià yǔ", meaning: "to rain" },
  { script: "想", romanization: "xiǎng", meaning: "to think" },
  { script: "小", romanization: "xiǎo", meaning: "small" },
  { script: "谢谢", romanization: "xiè xie", meaning: "to thank" },
  { script: "学生", romanization: "xué sheng", meaning: "student" },
  { script: "一", romanization: "yī", meaning: "one" },
  { script: "有", romanization: "yǒu", meaning: "to have" },
  { script: "昨天", romanization: "zuó tiān", meaning: "yesterday" },
  { script: "桌子", romanization: "zhuō zi", meaning: "table" },
  { script: "中国", romanization: "Zhōng guó", meaning: "China" },
  { script: "大学生", romanization: "dà xué sheng", meaning: "college student" },
  //{ script: "开", romanization: "kāi", meaning: "to open" },
  //{ script: "来", romanization: "lái", meaning: "to come" },
  //{ script: "后面", romanization: "hòu mian", meaning: "rear" },
  //{ script: "回", romanization: "huí", meaning: "to curve" },
  //{ script: "汉语", romanization: "Hàn yǔ", meaning: "Chinese language" },
  //{ script: "工作", romanization: "gōng zuò", meaning: "to work" },
  //{ script: "飞机", romanization: "fēi jī", meaning: "airplane" },
  //{ script: "分钟", romanization: "fēn zhōng", meaning: "minute" },
  //{ script: "高兴", romanization: "gāo xìng", meaning: "happy" },
  //{ script: "打电话", romanization: "dǎ diàn huà", meaning: "to make a telephone call" },
  // 
  /*
  { script: "里", romanization: "lǐ", meaning: "li (Chinese mile)" },
  { script: "零", romanization: "líng", meaning: "zero" },
  { script: "哪", romanization: "nǎ", meaning: "how" },
  { script: "那", romanization: "nà", meaning: "that" },
  { script: "呢", romanization: "ne", meaning: "particle indicating that a previously asked question is to be applied to the preceding word" },
  { script: "能", romanization: "néng", meaning: "to be able to" },
  { script: "年", romanization: "nián", meaning: "year" },
  { script: "钱", romanization: "qián", meaning: "coin" },
  { script: "前面", romanization: "qián miàn", meaning: "ahead" },
  { script: "请", romanization: "qǐng", meaning: "to ask" },
  { script: "热", romanization: "rè", meaning: "to warm up" },
  { script: "认识", romanization: "rèn shi", meaning: "to know" },
  { script: "日", romanization: "rì", meaning: "sun" },
  { script: "三", romanization: "sān", meaning: "three" },
  { script: "商店", romanization: "shāng diàn", meaning: "store" },
  { script: "上", romanization: "shàng", meaning: "on top" },
  { script: "上午", romanization: "shàng wǔ", meaning: "morning" },
  { script: "少", romanization: "shǎo", meaning: "few" },
  { script: "谁", romanization: "shéi", meaning: "who" },
  { script: "什么", romanization: "shén me", meaning: "what?" },
  { script: "十", romanization: "shí", meaning: "ten" },
  { script: "时候", romanization: "shí hou", meaning: "time" },
  { script: "睡觉", romanization: "shuì jiào", meaning: "to go to bed" },
  { script: "说话", romanization: "shuō huà", meaning: "to speak" },
  { script: "四", romanization: "sì", meaning: "four" },
  { script: "岁", romanization: "suì", meaning: "classifier for years (of age)" },
  { script: "他", romanization: "tā", meaning: "he or him" },
  { script: "她", romanization: "tā", meaning: "she" },
  { script: "太", romanization: "tài", meaning: "highest" },
  { script: "天气", romanization: "tiān qì", meaning: "weather" },
  { script: "听", romanization: "tīng", meaning: "to listen" },
  { script: "同学", romanization: "tóng xué", meaning: "to study at the same school" },
  { script: "喂", romanization: "wèi", meaning: "to feed" },
  { script: "下", romanization: "xià", meaning: "down" },
  { script: "下午", romanization: "xià wǔ", meaning: "afternoon" },
  { script: "先生", romanization: "xiān sheng", meaning: "teacher" },
  { script: "现在", romanization: "xiàn zài", meaning: "now" },
  { script: "小姐", romanization: "xiǎo jie", meaning: "young lady" },
  { script: "些", romanization: "xiē", meaning: "some" },
  { script: "写", romanization: "xiě", meaning: "to write" },
  { script: "星期", romanization: "xīng qī", meaning: "week" },
  { script: "学习", romanization: "xué xí", meaning: "to learn" },
  { script: "学校", romanization: "xué xiào", meaning: "school" },
  { script: "衣服", romanization: "yī fu", meaning: "clothes" },
  { script: "医生", romanization: "yī shēng", meaning: "doctor" },
  { script: "医院", romanization: "yī yuàn", meaning: "hospital" },
  { script: "椅子", romanization: "yǐ zi", meaning: "chair" },
  { script: "月", romanization: "yuè", meaning: "moon" },
  { script: "在", romanization: "zài", meaning: "(located) at" },
  { script: "再见", romanization: "zài jiàn", meaning: "goodbye" },
  { script: "怎么", romanization: "zěn me", meaning: "variant of 怎麼|怎么[zěn me]" },
  { script: "怎么样", romanization: "zěn me yàng", meaning: "how?" },
  { script: "这", romanization: "zhè", meaning: "this" },
  { script: "中午", romanization: "zhōng wǔ", meaning: "noon" },
  { script: "住", romanization: "zhù", meaning: "to live" },
  { script: "字", romanization: "zì", meaning: "letter" },
  { script: "坐", romanization: "zuò", meaning: "to sit" },
  { script: "做", romanization: "zuò", meaning: "to do" },*/
];
